### ISSUE TITLE
typit doesn't properly react to input anymore

### ISSUE THREAD

**Issue by technician77** [mrkkrp/typit#10] opened 2016-11-26 05:31 UTC
I use emacs GNU Emacs 25.1.1 (x86_64-w64-mingw32) of 2016-11-10. When I start typit-test it shows "Timer will start when you start typing…" Then it shows "typing..." when I type but the window does not show any reaction to my input. The highlighting remains on the first word even if i type the correct letters.

Well, it's not unlikely that some other package or some setting causes this. Do you have any suggestion what to look for? My config has become rather large. It will take a lot of time to find out when you have no idea where to look.

**Comment by mrkkrp** [comment] 2016-11-26 10:25
It works for me. Try with clean Emacs `emacs -Q` and only `typit` installed. The usual approach is to comment half of your customizations and see if the problem is still there. If it's there, then the problem in the other half (you again comment half of the rest). Binary search.

**Comment by technician77** [comment] 2016-11-29 01:58
I tracked it down - PEBKAC. Sorry about that. Typit works fine. The problem is just a visual problem. I use the integrated tango-dark theme. Until now it never let me down, but now it seems it seems the theme has problems to display the progress letter-typing of typit. I'll try to find out the problem in the theme. Maybe it's some customization I forgot about.

**Comment by technician77** [comment] 2016-11-29 02:25
Adding  :weight bold to the success face let's me track the character typed (correctly). It seems tango-dark does not theme :weight bold to the success face resulting it not to be visible when the word is highlighted. Would it make sense to let typit override the weight setting of the success face? This way it would work in typit without changing the face in general, wouldn't it?

**Comment by technician77** [comment] 2016-11-29 02:41
Added underline to the error face. This enables me to track the character where I am inside the current hightlighted word even if I made an error. I could have used weight bold as in success, but underline seems to be a better fit for an error.

**Comment by mrkkrp** [comment] 2016-11-29 10:08
Customize the `typit-correct-char` face and you should be OK. Closing for now.

**Closed as completed by mrkkrp** 2016-11-29 10:08 UTC
Labels: question
